package com.example.shirodemo.modules.sys.dataobject;

public class CourseInfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..course_info.id
     *
     * @mbg.generated Tue Jul 04 17:41:28 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..course_info.name
     *
     * @mbg.generated Tue Jul 04 17:41:28 CST 2023
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..course_info.id
     *
     * @return the value of test..course_info.id
     *
     * @mbg.generated Tue Jul 04 17:41:28 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..course_info.id
     *
     * @param id the value for test..course_info.id
     *
     * @mbg.generated Tue Jul 04 17:41:28 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..course_info.name
     *
     * @return the value of test..course_info.name
     *
     * @mbg.generated Tue Jul 04 17:41:28 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..course_info.name
     *
     * @param name the value for test..course_info.name
     *
     * @mbg.generated Tue Jul 04 17:41:28 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}