package com.example.shirodemo.modules.sys.dataobject;

public class CourseStudentInfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..course_student_info.id
     *
     * @mbg.generated Thu Jul 06 11:48:46 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..course_student_info.cs_id
     *
     * @mbg.generated Thu Jul 06 11:48:46 CST 2023
     */
    private Integer csId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..course_student_info.status
     *
     * @mbg.generated Thu Jul 06 11:48:46 CST 2023
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..course_student_info.class_num
     *
     * @mbg.generated Thu Jul 06 11:48:46 CST 2023
     */
    private Integer classNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..course_student_info.mark
     *
     * @mbg.generated Thu Jul 06 11:48:46 CST 2023
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..course_student_info.img_url
     *
     * @mbg.generated Thu Jul 06 11:48:46 CST 2023
     */
    private String imgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..course_student_info.id
     *
     * @return the value of test..course_student_info.id
     *
     * @mbg.generated Thu Jul 06 11:48:46 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..course_student_info.id
     *
     * @param id the value for test..course_student_info.id
     *
     * @mbg.generated Thu Jul 06 11:48:46 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..course_student_info.cs_id
     *
     * @return the value of test..course_student_info.cs_id
     *
     * @mbg.generated Thu Jul 06 11:48:46 CST 2023
     */
    public Integer getCsId() {
        return csId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..course_student_info.cs_id
     *
     * @param csId the value for test..course_student_info.cs_id
     *
     * @mbg.generated Thu Jul 06 11:48:46 CST 2023
     */
    public void setCsId(Integer csId) {
        this.csId = csId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..course_student_info.status
     *
     * @return the value of test..course_student_info.status
     *
     * @mbg.generated Thu Jul 06 11:48:46 CST 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..course_student_info.status
     *
     * @param status the value for test..course_student_info.status
     *
     * @mbg.generated Thu Jul 06 11:48:46 CST 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..course_student_info.class_num
     *
     * @return the value of test..course_student_info.class_num
     *
     * @mbg.generated Thu Jul 06 11:48:46 CST 2023
     */
    public Integer getClassNum() {
        return classNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..course_student_info.class_num
     *
     * @param classNum the value for test..course_student_info.class_num
     *
     * @mbg.generated Thu Jul 06 11:48:46 CST 2023
     */
    public void setClassNum(Integer classNum) {
        this.classNum = classNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..course_student_info.mark
     *
     * @return the value of test..course_student_info.mark
     *
     * @mbg.generated Thu Jul 06 11:48:46 CST 2023
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..course_student_info.mark
     *
     * @param mark the value for test..course_student_info.mark
     *
     * @mbg.generated Thu Jul 06 11:48:46 CST 2023
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..course_student_info.img_url
     *
     * @return the value of test..course_student_info.img_url
     *
     * @mbg.generated Thu Jul 06 11:48:46 CST 2023
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..course_student_info.img_url
     *
     * @param imgUrl the value for test..course_student_info.img_url
     *
     * @mbg.generated Thu Jul 06 11:48:46 CST 2023
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }
}