package com.example.shirodemo.modules.sys.dataobject;

public class CourseStudentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..course_student.id
     *
     * @mbg.generated Tue Jul 04 17:41:28 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..course_student.course_id
     *
     * @mbg.generated Tue Jul 04 17:41:28 CST 2023
     */
    private Integer courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..course_student.student_id
     *
     * @mbg.generated Tue Jul 04 17:41:28 CST 2023
     */
    private Integer studentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..course_student.id
     *
     * @return the value of test..course_student.id
     *
     * @mbg.generated Tue Jul 04 17:41:28 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..course_student.id
     *
     * @param id the value for test..course_student.id
     *
     * @mbg.generated Tue Jul 04 17:41:28 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..course_student.course_id
     *
     * @return the value of test..course_student.course_id
     *
     * @mbg.generated Tue Jul 04 17:41:28 CST 2023
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..course_student.course_id
     *
     * @param courseId the value for test..course_student.course_id
     *
     * @mbg.generated Tue Jul 04 17:41:28 CST 2023
     */
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..course_student.student_id
     *
     * @return the value of test..course_student.student_id
     *
     * @mbg.generated Tue Jul 04 17:41:28 CST 2023
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..course_student.student_id
     *
     * @param studentId the value for test..course_student.student_id
     *
     * @mbg.generated Tue Jul 04 17:41:28 CST 2023
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }
}