package com.example.shirodemo.modules.sys.dataobject;

public class CourseInfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..course_info.id
     *
     * @mbg.generated Wed Jul 05 18:25:47 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..course_info.name
     *
     * @mbg.generated Wed Jul 05 18:25:47 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..course_info.tag_id
     *
     * @mbg.generated Wed Jul 05 18:25:47 CST 2023
     */
    private Integer tagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..course_info.id
     *
     * @return the value of test..course_info.id
     *
     * @mbg.generated Wed Jul 05 18:25:47 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..course_info.id
     *
     * @param id the value for test..course_info.id
     *
     * @mbg.generated Wed Jul 05 18:25:47 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..course_info.name
     *
     * @return the value of test..course_info.name
     *
     * @mbg.generated Wed Jul 05 18:25:47 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..course_info.name
     *
     * @param name the value for test..course_info.name
     *
     * @mbg.generated Wed Jul 05 18:25:47 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..course_info.tag_id
     *
     * @return the value of test..course_info.tag_id
     *
     * @mbg.generated Wed Jul 05 18:25:47 CST 2023
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..course_info.tag_id
     *
     * @param tagId the value for test..course_info.tag_id
     *
     * @mbg.generated Wed Jul 05 18:25:47 CST 2023
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }
}