package com.example.shirodemo.modules.sys.dataobject;

public class PermissionDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..permission.id
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..permission.available
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    private Boolean available;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..permission.name
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..permission.parent_id
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..permission.parent_ids
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    private String parentIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..permission.permission
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    private String permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..permission.resource_type
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    private String resourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..permission.url
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..permission.id
     *
     * @return the value of test..permission.id
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..permission.id
     *
     * @param id the value for test..permission.id
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..permission.available
     *
     * @return the value of test..permission.available
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..permission.available
     *
     * @param available the value for test..permission.available
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..permission.name
     *
     * @return the value of test..permission.name
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..permission.name
     *
     * @param name the value for test..permission.name
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..permission.parent_id
     *
     * @return the value of test..permission.parent_id
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..permission.parent_id
     *
     * @param parentId the value for test..permission.parent_id
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..permission.parent_ids
     *
     * @return the value of test..permission.parent_ids
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public String getParentIds() {
        return parentIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..permission.parent_ids
     *
     * @param parentIds the value for test..permission.parent_ids
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public void setParentIds(String parentIds) {
        this.parentIds = parentIds == null ? null : parentIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..permission.permission
     *
     * @return the value of test..permission.permission
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..permission.permission
     *
     * @param permission the value for test..permission.permission
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public void setPermission(String permission) {
        this.permission = permission == null ? null : permission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..permission.resource_type
     *
     * @return the value of test..permission.resource_type
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..permission.resource_type
     *
     * @param resourceType the value for test..permission.resource_type
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..permission.url
     *
     * @return the value of test..permission.url
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..permission.url
     *
     * @param url the value for test..permission.url
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}