package com.example.shirodemo.modules.sys.dataobject;

public class StudentDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..student_info.id
     *
     * @mbg.generated Sat Jul 01 18:07:52 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..student_info.name
     *
     * @mbg.generated Sat Jul 01 18:07:52 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..student_info.age
     *
     * @mbg.generated Sat Jul 01 18:07:52 CST 2023
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..student_info.phone
     *
     * @mbg.generated Sat Jul 01 18:07:52 CST 2023
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..student_info.sub
     *
     * @mbg.generated Sat Jul 01 18:07:52 CST 2023
     */
    private Long sub;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..student_info.openId
     *
     * @mbg.generated Sat Jul 01 18:07:52 CST 2023
     */
    private String openid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..student_info.id
     *
     * @return the value of test..student_info.id
     *
     * @mbg.generated Sat Jul 01 18:07:52 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..student_info.id
     *
     * @param id the value for test..student_info.id
     *
     * @mbg.generated Sat Jul 01 18:07:52 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..student_info.name
     *
     * @return the value of test..student_info.name
     *
     * @mbg.generated Sat Jul 01 18:07:52 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..student_info.name
     *
     * @param name the value for test..student_info.name
     *
     * @mbg.generated Sat Jul 01 18:07:52 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..student_info.age
     *
     * @return the value of test..student_info.age
     *
     * @mbg.generated Sat Jul 01 18:07:52 CST 2023
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..student_info.age
     *
     * @param age the value for test..student_info.age
     *
     * @mbg.generated Sat Jul 01 18:07:52 CST 2023
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..student_info.phone
     *
     * @return the value of test..student_info.phone
     *
     * @mbg.generated Sat Jul 01 18:07:52 CST 2023
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..student_info.phone
     *
     * @param phone the value for test..student_info.phone
     *
     * @mbg.generated Sat Jul 01 18:07:52 CST 2023
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..student_info.sub
     *
     * @return the value of test..student_info.sub
     *
     * @mbg.generated Sat Jul 01 18:07:52 CST 2023
     */
    public Long getSub() {
        return sub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..student_info.sub
     *
     * @param sub the value for test..student_info.sub
     *
     * @mbg.generated Sat Jul 01 18:07:52 CST 2023
     */
    public void setSub(Long sub) {
        this.sub = sub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..student_info.openId
     *
     * @return the value of test..student_info.openId
     *
     * @mbg.generated Sat Jul 01 18:07:52 CST 2023
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..student_info.openId
     *
     * @param openid the value for test..student_info.openId
     *
     * @mbg.generated Sat Jul 01 18:07:52 CST 2023
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    @Override
    public String toString() {
        return "StudentDO{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", age=" + age +
                ", phone='" + phone + '\'' +
                ", sub=" + sub +
                ", openid='" + openid + '\'' +
                '}';
    }
}