package com.example.shirodemo.modules.sys.dataobject;

import java.util.Date;

public class TemplateDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..msg_template.id
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..msg_template.appid
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    private String appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..msg_template.template_id
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    private String templateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..msg_template.name
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..msg_template.title
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..msg_template.url
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..msg_template.status
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..msg_template.update_time
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..msg_template.id
     *
     * @return the value of test..msg_template.id
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..msg_template.id
     *
     * @param id the value for test..msg_template.id
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..msg_template.appid
     *
     * @return the value of test..msg_template.appid
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..msg_template.appid
     *
     * @param appid the value for test..msg_template.appid
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..msg_template.template_id
     *
     * @return the value of test..msg_template.template_id
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..msg_template.template_id
     *
     * @param templateId the value for test..msg_template.template_id
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId == null ? null : templateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..msg_template.name
     *
     * @return the value of test..msg_template.name
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..msg_template.name
     *
     * @param name the value for test..msg_template.name
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..msg_template.title
     *
     * @return the value of test..msg_template.title
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..msg_template.title
     *
     * @param title the value for test..msg_template.title
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..msg_template.url
     *
     * @return the value of test..msg_template.url
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..msg_template.url
     *
     * @param url the value for test..msg_template.url
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..msg_template.status
     *
     * @return the value of test..msg_template.status
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..msg_template.status
     *
     * @param status the value for test..msg_template.status
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..msg_template.update_time
     *
     * @return the value of test..msg_template.update_time
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..msg_template.update_time
     *
     * @param updateTime the value for test..msg_template.update_time
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}