package com.example.shirodemo.modules.sys.dataobject;

public class TemplateInfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..template_info.template_id
     *
     * @mbg.generated Sun Jul 02 16:57:02 CST 2023
     */
    private String templateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..template_info.title
     *
     * @mbg.generated Sun Jul 02 16:57:02 CST 2023
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..template_info.primary_industry
     *
     * @mbg.generated Sun Jul 02 16:57:02 CST 2023
     */
    private String primaryIndustry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..template_info.deputy_industry
     *
     * @mbg.generated Sun Jul 02 16:57:02 CST 2023
     */
    private String deputyIndustry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..template_info.content
     *
     * @mbg.generated Sun Jul 02 16:57:02 CST 2023
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..template_info.example
     *
     * @mbg.generated Sun Jul 02 16:57:02 CST 2023
     */
    private String example;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..template_info.template_id
     *
     * @return the value of test..template_info.template_id
     *
     * @mbg.generated Sun Jul 02 16:57:02 CST 2023
     */
    public String getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..template_info.template_id
     *
     * @param templateId the value for test..template_info.template_id
     *
     * @mbg.generated Sun Jul 02 16:57:02 CST 2023
     */
    public void setTemplateId(String templateId) {
        this.templateId = templateId == null ? null : templateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..template_info.title
     *
     * @return the value of test..template_info.title
     *
     * @mbg.generated Sun Jul 02 16:57:02 CST 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..template_info.title
     *
     * @param title the value for test..template_info.title
     *
     * @mbg.generated Sun Jul 02 16:57:02 CST 2023
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..template_info.primary_industry
     *
     * @return the value of test..template_info.primary_industry
     *
     * @mbg.generated Sun Jul 02 16:57:02 CST 2023
     */
    public String getPrimaryIndustry() {
        return primaryIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..template_info.primary_industry
     *
     * @param primaryIndustry the value for test..template_info.primary_industry
     *
     * @mbg.generated Sun Jul 02 16:57:02 CST 2023
     */
    public void setPrimaryIndustry(String primaryIndustry) {
        this.primaryIndustry = primaryIndustry == null ? null : primaryIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..template_info.deputy_industry
     *
     * @return the value of test..template_info.deputy_industry
     *
     * @mbg.generated Sun Jul 02 16:57:02 CST 2023
     */
    public String getDeputyIndustry() {
        return deputyIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..template_info.deputy_industry
     *
     * @param deputyIndustry the value for test..template_info.deputy_industry
     *
     * @mbg.generated Sun Jul 02 16:57:02 CST 2023
     */
    public void setDeputyIndustry(String deputyIndustry) {
        this.deputyIndustry = deputyIndustry == null ? null : deputyIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..template_info.content
     *
     * @return the value of test..template_info.content
     *
     * @mbg.generated Sun Jul 02 16:57:02 CST 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..template_info.content
     *
     * @param content the value for test..template_info.content
     *
     * @mbg.generated Sun Jul 02 16:57:02 CST 2023
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..template_info.example
     *
     * @return the value of test..template_info.example
     *
     * @mbg.generated Sun Jul 02 16:57:02 CST 2023
     */
    public String getExample() {
        return example;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..template_info.example
     *
     * @param example the value for test..template_info.example
     *
     * @mbg.generated Sun Jul 02 16:57:02 CST 2023
     */
    public void setExample(String example) {
        this.example = example == null ? null : example.trim();
    }
}