package com.example.shirodemo.modules.sys.dataobject;

public class TemplateDOWithBLOBs extends TemplateDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..msg_template.content
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..msg_template.data
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    private String data;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..msg_template.miniprogram
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    private String miniprogram;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..msg_template.content
     *
     * @return the value of test..msg_template.content
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..msg_template.content
     *
     * @param content the value for test..msg_template.content
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..msg_template.data
     *
     * @return the value of test..msg_template.data
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..msg_template.data
     *
     * @param data the value for test..msg_template.data
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..msg_template.miniprogram
     *
     * @return the value of test..msg_template.miniprogram
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    public String getMiniprogram() {
        return miniprogram;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..msg_template.miniprogram
     *
     * @param miniprogram the value for test..msg_template.miniprogram
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    public void setMiniprogram(String miniprogram) {
        this.miniprogram = miniprogram == null ? null : miniprogram.trim();
    }
}