package com.example.shirodemo.modules.sys.dataobject;

public class UserRoleDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..user_role.uid
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..user_role.role_id
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..user_role.uid
     *
     * @return the value of test..user_role.uid
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..user_role.uid
     *
     * @param uid the value for test..user_role.uid
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..user_role.role_id
     *
     * @return the value of test..user_role.role_id
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..user_role.role_id
     *
     * @param roleId the value for test..user_role.role_id
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}