package com.example.shirodemo.modules.sys.dataobject;

public class UserDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..user_info.uid
     *
     * @mbg.generated Wed Jun 28 15:05:32 CST 2023
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..user_info.name
     *
     * @mbg.generated Wed Jun 28 15:05:32 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..user_info.password
     *
     * @mbg.generated Wed Jun 28 15:05:32 CST 2023
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..user_info.state
     *
     * @mbg.generated Wed Jun 28 15:05:32 CST 2023
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..user_info.account
     *
     * @mbg.generated Wed Jun 28 15:05:32 CST 2023
     */
    private String account;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..user_info.uid
     *
     * @return the value of test..user_info.uid
     *
     * @mbg.generated Wed Jun 28 15:05:32 CST 2023
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..user_info.uid
     *
     * @param uid the value for test..user_info.uid
     *
     * @mbg.generated Wed Jun 28 15:05:32 CST 2023
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..user_info.name
     *
     * @return the value of test..user_info.name
     *
     * @mbg.generated Wed Jun 28 15:05:32 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..user_info.name
     *
     * @param name the value for test..user_info.name
     *
     * @mbg.generated Wed Jun 28 15:05:32 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..user_info.password
     *
     * @return the value of test..user_info.password
     *
     * @mbg.generated Wed Jun 28 15:05:32 CST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..user_info.password
     *
     * @param password the value for test..user_info.password
     *
     * @mbg.generated Wed Jun 28 15:05:32 CST 2023
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..user_info.state
     *
     * @return the value of test..user_info.state
     *
     * @mbg.generated Wed Jun 28 15:05:32 CST 2023
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..user_info.state
     *
     * @param state the value for test..user_info.state
     *
     * @mbg.generated Wed Jun 28 15:05:32 CST 2023
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..user_info.account
     *
     * @return the value of test..user_info.account
     *
     * @mbg.generated Wed Jun 28 15:05:32 CST 2023
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..user_info.account
     *
     * @param account the value for test..user_info.account
     *
     * @mbg.generated Wed Jun 28 15:05:32 CST 2023
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }
}