package com.example.shirodemo.dao;

import com.example.shirodemo.dataobject.PermissionDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PermissionDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..permission
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..permission
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    int insert(PermissionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..permission
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    int insertSelective(PermissionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..permission
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    PermissionDO selectByPrimaryKey(Integer id);

    List<PermissionDO> selectByRoleId(Integer id);

    List<PermissionDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..permission
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    int updateByPrimaryKeySelective(PermissionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..permission
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    int updateByPrimaryKey(PermissionDO record);
}