package com.example.shirodemo.dao;

import com.example.shirodemo.dataobject.RoleDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface RoleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..role
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..role
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    int insert(RoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..role
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    int insertSelective(RoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..role
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    RoleDO selectByPrimaryKey(Integer id);

    RoleDO selectByRole(String role);

    List<RoleDO> selectByUserAccount(String account);

    List<RoleDO> selectALL();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..role
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    int updateByPrimaryKeySelective(RoleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..role
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    int updateByPrimaryKey(RoleDO record);
}