package com.example.shirodemo.modules.sys.dao;

import com.example.shirodemo.modules.sys.dataobject.CourseStudentInfoDO;
import org.springframework.stereotype.Repository;

@Repository
public interface CourseStudentInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..course_student_info
     *
     * @mbg.generated Thu Jul 06 11:48:46 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..course_student_info
     *
     * @mbg.generated Thu Jul 06 11:48:46 CST 2023
     */
    int insert(CourseStudentInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..course_student_info
     *
     * @mbg.generated Thu Jul 06 11:48:46 CST 2023
     */
    int insertSelective(CourseStudentInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..course_student_info
     *
     * @mbg.generated Thu Jul 06 11:48:46 CST 2023
     */
    CourseStudentInfoDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..course_student_info
     *
     * @mbg.generated Thu Jul 06 11:48:46 CST 2023
     */
    int updateByPrimaryKeySelective(CourseStudentInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..course_student_info
     *
     * @mbg.generated Thu Jul 06 11:48:46 CST 2023
     */
    int updateByPrimaryKey(CourseStudentInfoDO record);
}