package com.example.shirodemo.modules.sys.dao;

import com.example.shirodemo.modules.sys.dataobject.MemberDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface MemberDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..member_info
     *
     * @mbg.generated Sun Jul 02 14:31:53 CST 2023
     */
    int deleteByPrimaryKey(String openid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..member_info
     *
     * @mbg.generated Sun Jul 02 14:31:53 CST 2023
     */
    int insert(MemberDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..member_info
     *
     * @mbg.generated Sun Jul 02 14:31:53 CST 2023
     */
    int insertSelective(MemberDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..member_info
     *
     * @mbg.generated Sun Jul 02 14:31:53 CST 2023
     */
    MemberDO selectByPrimaryKey(String openid);

    List<MemberDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..member_info
     *
     * @mbg.generated Sun Jul 02 14:31:53 CST 2023
     */
    int updateByPrimaryKeySelective(MemberDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..member_info
     *
     * @mbg.generated Sun Jul 02 14:31:53 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(MemberDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..member_info
     *
     * @mbg.generated Sun Jul 02 14:31:53 CST 2023
     */
    int updateByPrimaryKey(MemberDO record);
}