package com.example.shirodemo.modules.sys.dao;

import com.example.shirodemo.modules.sys.dataobject.StudentDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface StudentDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..student_info
     *
     * @mbg.generated Sat Jul 01 18:07:52 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..student_info
     *
     * @mbg.generated Sat Jul 01 18:07:52 CST 2023
     */
    int insert(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..student_info
     *
     * @mbg.generated Sat Jul 01 18:07:52 CST 2023
     */
    int insertSelective(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..student_info
     *
     * @mbg.generated Sat Jul 01 18:07:52 CST 2023
     */
    StudentDO selectByPrimaryKey(Integer id);

    StudentDO selectByNameAndPhone(String name,String phone);

    List<StudentDO> selectAll();

    List<StudentDO> selectByPhone(String phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..student_info
     *
     * @mbg.generated Sat Jul 01 18:07:52 CST 2023
     */
    int updateByPrimaryKeySelective(StudentDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..student_info
     *
     * @mbg.generated Sat Jul 01 18:07:52 CST 2023
     */
    int updateByPrimaryKey(StudentDO record);
}