package com.example.shirodemo.modules.sys.dao;

import com.example.shirodemo.modules.sys.dataobject.TemplateInfoDO;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TemplateInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..template_info
     *
     * @mbg.generated Sun Jul 02 16:57:02 CST 2023
     */
    int deleteByPrimaryKey(String templateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..template_info
     *
     * @mbg.generated Sun Jul 02 16:57:02 CST 2023
     */
    int insert(TemplateInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..template_info
     *
     * @mbg.generated Sun Jul 02 16:57:02 CST 2023
     */
    int insertSelective(TemplateInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..template_info
     *
     * @mbg.generated Sun Jul 02 16:57:02 CST 2023
     */
    TemplateInfoDO selectByPrimaryKey(String templateId);

    List<TemplateInfoDO> getAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..template_info
     *
     * @mbg.generated Sun Jul 02 16:57:02 CST 2023
     */
    int updateByPrimaryKeySelective(TemplateInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..template_info
     *
     * @mbg.generated Sun Jul 02 16:57:02 CST 2023
     */
    int updateByPrimaryKey(TemplateInfoDO record);
}