package com.example.shirodemo.modules.sys.dao;

import com.example.shirodemo.modules.sys.dataobject.TemplateDO;
import com.example.shirodemo.modules.sys.dataobject.TemplateDOWithBLOBs;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface TemplateDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..msg_template
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..msg_template
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    int insert(TemplateDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..msg_template
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    int insertSelective(TemplateDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..msg_template
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    TemplateDOWithBLOBs selectByPrimaryKey(Long id);

    List<TemplateDOWithBLOBs> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..msg_template
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    int updateByPrimaryKeySelective(TemplateDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..msg_template
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(TemplateDOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test..msg_template
     *
     * @mbg.generated Sun Jul 02 14:30:24 CST 2023
     */
    int updateByPrimaryKey(TemplateDO record);
}