package com.example.shirodemo.dataobject;

public class RoleDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..role.id
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..role.available
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    private Boolean available;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..role.description
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test..role.role
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..role.id
     *
     * @return the value of test..role.id
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..role.id
     *
     * @param id the value for test..role.id
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..role.available
     *
     * @return the value of test..role.available
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..role.available
     *
     * @param available the value for test..role.available
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..role.description
     *
     * @return the value of test..role.description
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..role.description
     *
     * @param description the value for test..role.description
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test..role.role
     *
     * @return the value of test..role.role
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test..role.role
     *
     * @param role the value for test..role.role
     *
     * @mbg.generated Wed Jun 28 14:07:04 CST 2023
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }
}